---
- name: "🔗 Include Install packages tasks"
  include_tasks: "install-{{ ansible_os_family | lower }}.yml"
  when: input_install_docker | default(true)

- name: "🔗 Include tasks Register gitlab runner"
  include_tasks: "register-gitlab-runner.yml"
  loop: "{{ input_gitlab_runner_configuration.runners }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.register_runner.id is not defined
    - item.register_runner.token is not defined
    - item.register_runner.id | default(None) is none
    - item.register_runner.token | default('') | length == 0

- name: "🔗 Include tasks Configuration gitlab-runner"
  include_tasks: config-gitlab-runner.yml
