---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: deploy-gitlab-runner
      vars:
        input_debug: true
        input_gitlab_runner_configuration:
          concurrent: 100
          check_interval: 0
          shutdown_timeout: 0
          session_timeout: 3600
          runners:
            - name: "molecule test"
              url: "https://gitlab.com"
              register_runner:
                id: "{{ lookup('env', 'GITLAB_RUNNER_ID') }}"
                register_gitlab_api_token: "{{ lookup('env', 'GITLAB_TOKEN') }}"
                description: "molecule test"
                tag_list: ["none"]
                runner_type: "group_type"
                group_id: "{{ lookup('env', 'GITLAB_GROUP_REPOSITORY_ID') }}"
                access_level: "not_protected"
                token: "{{ lookup('env', 'GITLAB_RUNNER_TOKEN') }}"
              executor: "docker"
              docker:
                tls_verify: false
                image: "docker:latest"
                privileged: true
                disable_entrypoint_overwrite: false
                oom_kill_disable: false
                disable_cache: false
                volumes:
                  - "/cache"
                  - "/var/run/docker.sock:/var/run/docker.sock"
                shm_size: 0
